name: Check valid plumber.R file

on:
  push:
    branches: [master, dev]

jobs:
  Rscript:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: install plumber deps
        run: brew update && brew install libsodium udunits pkg-config gdal
      - name: Rscript plumber.R
        run: | 
          Rscript -e 'install.packages("plumber");r = plumber::plumb(file.path("R", "plumber.R"))'